--Drops tablas
DROP TABLE C_HASHTAG.Rol_Usuario
DROP TABLE C_HASHTAG.Rubro_Publicacion
DROP TABLE C_HASHTAG.Oferta
DROP TABLE C_HASHTAG.Calificacion
DROP TABLE C_HASHTAG.Item
DROP TABLE C_HASHTAG.Factura
DROP TABLE C_HASHTAG.Compra
DROP TABLE C_HASHTAG.Publicacion
DROP TABLE C_HASHTAG.Tipo
DROP TABLE C_HASHTAG.Usuario
DROP TABLE C_HASHTAG.Visibilidad
DROP TABLE C_HASHTAG.Estado
DROP TABLE C_HASHTAG.Empresa
DROP TABLE C_HASHTAG.Rubro
DROP TABLE C_HASHTAG.Cliente
DROP TABLE C_HASHTAG.Documento
DROP TABLE C_HASHTAG.Funcionalidad_Rol
DROP TABLE C_HASHTAG.Funcionalidad
DROP TABLE C_HASHTAG.Rol

--Drop esquema
DROP SCHEMA C_HASHTAG
